name: Build AppCast for TM (tm-v only)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  appcast:
    runs-on: windows-latest
    steps:
      - name: Check if tag starts with tm-v
        id: tagcheck
        shell: pwsh
        run: |
          $tag = "${{ github.event.release.tag_name }}"
          if ($tag -notmatch '^tm-v') {
            Write-Host "Tag does not start with tm-v → skip"
            "skip=true"  | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding ascii
          }
          else {
            "skip=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding ascii
          }

      - name: Stop if tag does not match tm-v
        if: steps.tagcheck.outputs.skip == 'true'
        run: echo "Skipping non-TM release."

      - name: Checkout repo (on default branch)
        if: steps.tagcheck.outputs.skip == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      # ✅ Git EOL 변환 방지 + .gitattributes 설정
      - name: Disable EOL conversion & set attributes
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        run: |
          git config core.autocrlf false
          git config core.eol lf
          if (-not (Test-Path .gitattributes)) { New-Item -ItemType File -Path .gitattributes | Out-Null }
          # here-string 대신 안전하게 한 줄씩 추가
          Add-Content -Path .gitattributes -Value "tm_update/appcast.xml -text"
          Add-Content -Path .gitattributes -Value "tm_update/appcast.xml.signature -text"

      - name: Setup .NET
        if: steps.tagcheck.outputs.skip == 'false'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install NetSparkle AppCast tool
        if: steps.tagcheck.outputs.skip == 'false'
        run: dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator

      - name: Restore signing keys
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        run: |
          $KeyDir = "$env:LOCALAPPDATA\Netsparkle"
          New-Item -ItemType Directory -Force -Path $KeyDir | Out-Null
          Set-Content -Path (Join-Path $KeyDir 'NetSparkle_Ed25519.priv') -Value '${{ secrets.NETSPARKLE_PRIV }}' -NoNewline -Encoding ascii
          Set-Content -Path (Join-Path $KeyDir 'NetSparkle_Ed25519.pub')  -Value '${{ secrets.NETSPARKLE_PUB }}'  -NoNewline -Encoding ascii

      - name: Echo public key for sanity check
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        run: |
          $pubPath = Join-Path $env:LOCALAPPDATA 'Netsparkle\NetSparkle_Ed25519.pub'
          $pub = Get-Content $pubPath -Raw
          Write-Host "NetSparkle public key (Base64) used by generator:"
          Write-Host $pub

      - name: Download latest TM release asset
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        env:
          REPO: ${{ github.repository }}
          TAG:  ${{ github.event.release.tag_name }}
        run: |
          $api = "https://api.github.com/repos/$env:REPO/releases/tags/$env:TAG"
          $headers = @{ "User-Agent" = "gh-actions-appcast" }
          $r = Invoke-RestMethod -Uri $api -Headers $headers -Method Get -UseBasicParsing

          $asset = $r.assets | Where-Object { $_.name -match '\.msi$' } | Select-Object -First 1
          if (-not $asset) { $asset = $r.assets | Where-Object { $_.name -match '\.exe$' } | Select-Object -First 1 }
          if (-not $asset) { throw "No MSI/EXE asset found on release $env:TAG" }

          $dlDir = "_tmp_download"
          New-Item -ItemType Directory -Force -Path $dlDir | Out-Null
          $local = Join-Path $dlDir $asset.name
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $local -UseBasicParsing

          "ASSET_PATH=$local" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding ascii

      - name: Generate TM AppCast
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        env:
          TAG:   ${{ github.event.release.tag_name }}
          BIN:   ${{ env.ASSET_PATH }}
          OWNER: ${{ github.repository_owner }}
          REPO:  ${{ github.event.repository.name }}
        run: |
          $ErrorActionPreference = 'Stop'
          $outDir = "appcast_out"
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null

          $version = $env:TAG -replace '^tm-v',''
          $baseUrl = "https://github.com/$($env:OWNER)/$($env:REPO)/releases/download/$($env:TAG)"

          $tool = "$env:USERPROFILE\.dotnet\tools\netsparkle-generate-appcast.exe"
          & $tool `
            -a $outDir `
            --single-file "$env:BIN" `
            -o windows `
            -n "TM Server" `
            --output-type xml `
            --human-readable `
            -u $baseUrl `
            --file-version $version

      - name: Sanity check (file size & presence)
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        run: |
          $xml = [xml](Get-Content appcast_out/appcast.xml -Raw)
          $enc = $xml.rss.channel.item.enclosure
          $lenXml = [int64]$enc.length
          $fileOnDisk = "${{ env.ASSET_PATH }}"
          $lenReal = (Get-Item $fileOnDisk).Length
          if ($lenXml -ne $lenReal) { throw "Length mismatch: appcast=$lenXml, file=$lenReal" }
          if (-not (Test-Path appcast_out/appcast.xml.signature)) { throw "Missing appcast.xml.signature" }
          Write-Host "Sanity OK: length matches and signature file exists."

      - name: Move TM appcast files
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "tm_update" | Out-Null
          Copy-Item "appcast_out/appcast.xml"           "tm_update/appcast.xml"           -Force
          Copy-Item "appcast_out/appcast.xml.signature" "tm_update/appcast.xml.signature" -Force

      - name: Commit and push
        if: steps.tagcheck.outputs.skip == 'false'
        shell: pwsh
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add .gitattributes tm_update/appcast.xml tm_update/appcast.xml.signature
          git commit -m "chore(appcast): update for ${{ github.event.release.tag_name }}" || echo "Nothing to commit"
          git push origin ${{ github.event.repository.default_branch }}
