name: Generate Appcast on Release

on:
  release:
    types: [published]

jobs:
  generate-appcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find MSI asset
        id: find_msi
        run: |
          MSI_URL=$(echo "${{ toJSON(github.event.release.assets) }}" | jq -r '.[] | select(.name | endswith(".msi")) | .browser_download_url')
          MSI_NAME=$(echo "${{ toJSON(github.event.release.assets) }}" | jq -r '.[] | select(.name | endswith(".msi")) | .name')
          if [ -z "$MSI_URL" ]; then
            echo "Error: No .msi file found in the release assets."
            exit 1
          fi
          echo "url=$MSI_URL" >> $GITHUB_OUTPUT
          echo "name=$MSI_NAME" >> $GITHUB_OUTPUT
          echo "Found MSI: $MSI_NAME at $MSI_URL"

      - name: Download MSI asset
        run: |
          wget -q -O ${{ steps.find_msi.outputs.name }} ${{ steps.find_msi.outputs.url }}
          echo "MSI file downloaded."

      - name: Generate appcast file
        shell: pwsh
        run: |
          Write-Host "Testing PowerShell block"
          # 임시로 최소화, 나중에 로직 복원

      - name: Commit and push appcast
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./appcast/tm.xml
          git commit -m "Update appcast for release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push || echo "Nothing to push"
